#!/bin/zsh

alias zshrc='vim ~/.zshrc'
alias gitrc='vim ~/.gitconfig'
alias vimrc='vim ~/.vimrc'

# shell
alias lsh='ls -a'
alias lsl='ls -l -G'
alias ps='ps -xva'

# webdev
alias bower='noglob bower'
alias pg='postgres -D /usr/local/var/postgres'
alias be='bundle exec'
