#!/bin/zsh
alias gitrc="$EDITOR ~/.gitconfig"
alias vimrc="$EDITOR ~/.vimrc"

# overrides
alias cat="bat"
alias find="fd"
alias top="htop"
alias du="ncdu --color dark -rr -x"
alias ls="exa"
alias lsx="exa --git-ignore"
alias ps="procs"

# shell
alias lsl="ls -l"

# tools
alias fzp="fzf --preview 'bat --color \"always\" {}'"

# webdev
alias pg="postgres -D /usr/local/var/postgres"
alias be="bundle exec"
alias bs="bundle exec spring"
alias dc=docker-compose
alias dm=docker-machine

# gamedev
alias butler="$HOME/Library/Application\ Support/itch/apps/butler/butler"
alias aseprite="/Applications/Aseprite.app/Contents/MacOS/aseprite"

