#!/bin/zsh

function zshrc() {
  if [[ "$1" == "-h" ]]; then
    echo "usage: zshrc [-h] [module_path]"
  elif [[ -z "$1" ]]; then
    vim $ZSH_RC
  elif [[ -f $ZSH_RCD/$1 ]]; then
    vim $ZSH_RCD/$1
  else
    echo "$1 is not a known config module."
  fi
}
