#!/bin/zsh

## postgres
export PGDATA=/usr/local/var/postgres

# android
export ANDROID_SDK_ROOT=~/Library/Android/sdk

## nvm
export NVM_DIR=~/.nvm

## python
export PIP_REQUIRE_VIRTUALENV=true

function gpip() {
  PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

