#!/bin/bash

# -- cosmetics --
nc="\033[0m"
white="\033[1;37m"
green="\033[0;32m"
red="\033[0;31m"
gray="\033[0;37m"

# -- config --
declare -a exclusions=(
  "."
  ".."
  ".git"
  ".gitignore"
  "install"
  "README.md"
  ".DS_Store"
)

home_directory="$HOME/"
repo_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/"

# -- impls --
# -- impls/options
usage() {
  echo "usage: install [-chv]" 1>&2; exit 1;
}

while getopts ":chv" option; do
  case "${option}" in
    c) clean_links=1 ;;
    v) verbose=1 ;;
    *) usage ;;
  esac
done

# -- impls/helpers
prompt_for_skip() {
  while true; do
    read -r result
    case $result in
      [Bb]* ) echo 0; break;;
      [Ss]* ) echo 1; break;;
    esac
  done
}

# -- impls/main

# symlink all configs in this dir
for entry in * .*; do
  # skip any entries from the exclusions array
  if [[ ${exclusions[*]} =~ $entry ]]; then
    continue
  fi

  home_filepath=$home_directory$entry
  repo_filepath=$repo_directory$entry

  # if cleaning, check if the item is a symlink, and if so remove it
  if [ -n "${clean_links}" ]; then
    if [ -L "$home_filepath" ]; then
      echo -e "${red}✗ ${white}removing link: ${gray}$home_filepath${nc}"
      rm -r "$home_filepath"
    fi
    continue
  fi

  # otherwise, we're linking
  if [ -L "$home_filepath" ]; then
    echo -e "${green}✓ ${white}link exists: ${gray}$home_filepath${nc}"
    continue
  fi

  # if there's a file there there that isn't a link, try to back it up
  if [ -e "$home_filepath" ]; then
    echo -e "${red}✗ ${white}file exists: ${gray}$home_filepath${white}. (b)ackup or (s)kip?${nc}"
    if [ "$(prompt_for_skip)" == "1" ]; then
      continue
    else
      mv -f "$home_filepath" "$home_filepath.bak"
    fi
  else
    echo -e "${green}• ${white}file did not exist, linking: ${gray}$home_filepath${nc}"
  fi

  # and then create the symlink
  ln -sF "$repo_filepath" "$home_filepath"
done

# - install homebrew if necessary
if ! [ -x "$(command -v brew)" ]; then
  echo -e "${green}• ${white}brew was not installed, installing${nc}"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo -e "${green}✓ ${white}brew exists: ${gray}$(command -v brew)${nc}"
fi

# - install brew packages
echo -e "${green}• ${white}installing brew packages${nc}"

if [ -n "${verbose}" ]; then
  brew bundle --global -v
else
  brew bundle --global
fi

# - install vim plugins
echo -e "${green}• ${white}installing vim plugins${nc}"
vim +"PlugInstall" +qall &> /dev/null
