#!/bin/sh
. prelude

# -- parsing --
Usage() {
  pu "[-h] <in> [<out>]"
}

while getopts ":h" option; do
  case "${option}" in
    h*) Usage ;;
  esac
done

# -- commands --
Convert() {
  ffmpeg \
    -i "$1" \
    -filter_complex "[0:v] fps=12,scale=600:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" \
    -f gif - \
    |
    gifsicle \
      --optimize=3 \
      --delay=7 \
      > \
      "$2"
}

# -- main --
Main() {
  # require input path
  in="$1"; shift
  Require "$in"
  RequireExists "$in"

  # create a same-named gif in this dir if out path is unspecified
  out="$1"; shift
  if [ -z "$out" ]; then
    out="$in"
    out="${out##*/}"
    out="${out%%.*}.gif"
  fi

  # convert mov
  Convert "$in" "$out"
}

Main "$@"
