#!/bin/sh
. prelude

# -- constants --
NOTES_DIR="$HOME/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents/Notes"

# shellcheck disable=SC2016
CLEAN_AWK='{
  sub(/\..*/, "", $1) # strip ext
  sub(/./, tolower(substr($1, 1, 1)), $1) # uncapitalize
  print($1)
}'

# -- parsing --
Usage() {
  pu "[-h] <list|open|name>"
}

while getopts ":h" option; do
  case "${option}" in
    h*) Usage ;;
  esac
done

# -- commands --
# lists existing notes
ListNotes() {
  find "$NOTES_DIR" -type f -name "*.md" -exec basename {} ';' \
    | awk "$CLEAN_AWK"
}

# opens the notes dir
OpenDir() {
  open "$NOTES_DIR"
}

# creates a note if necessary and edits it
OpenNote() {
  FindPath "$1"
  CheckType
  CreateNote
  EditNote
}

# -- c/helpers
EditNote() {
  ia "$path.md"
}

CheckType() {
  if [ -f "$path.txt" ]; then
    mv "$path.txt" "$path.md"
  fi
}

CreateNote() {
  if [ -f "$path.md" ]; then
    return 0
  fi

  pe "file does not exist: ${ga}$name.md"
  pi "create it? ${ga}[yn]"

  read -r confirm
  if [ "$confirm" = "y" ]; then
    touch "$path.md"
  else
    exit 0;
  fi
}

# -- queries --
FindPath() {
  name=$(
    echo "$1" \
      | awk "$CLEAN_AWK"
  )

  name="${name%.*}"
  path="$NOTES_DIR/$name"
}

# -- main --
Main() {
  # validate args
  raw="$1"; shift
  Require "$raw"

  # dispatch command
  if [ "$raw" = "list" ]; then
    ListNotes
  elif [ "$raw" = "open" ]; then
    OpenDir
  else 
    OpenNote "$raw"
  fi
}

Main "$*"
