#!/bin/sh
. prelude

# -- constants --
NOTES_DIR="$HOME/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents/Notes"

# -- parsing --
Usage() {
  pu "[-h] <name>"
}

while getopts ":h" option; do
  case "${option}" in
    h*) Usage ;;
  esac
done

# -- commands --
EditNote() {
  ia "$path.md"
}

CheckType() {
  if [ -f "$path.txt" ]; then
    mv "$path.txt" "$path.md"
  fi
}

CreateNote() {
  if [ -f "$path.md" ]; then
    return 0
  fi

  pe "file does not exist: ${ga}$name"
  pi "create it? ${ga}[yn]"

  read -r confirm
  if [ "$confirm" = "y" ]; then
    touch "$path.md"
  else
    exit 0;
  fi
}

# -- queries --
FindPath() {
  name=$(
    echo "$1" \
      | awk '{ sub(".", toupper(substr($1, 1, 1)), $1); print($1) }' \
  )

  path="$NOTES_DIR/$name"
}

# -- main --
Main() {
  # validate args
  raw="$1"; shift
  Require "$raw"

  # create the note if necessary and edit it
  FindPath "$raw"
  CheckType
  CreateNote
  EditNote
}

Main "$*"
