#!/bin/zsh

# parse options
usage() { 
  echo "usage: rezsh [-hv]" 1>&2; exit 1; 
}

while getopts ":hv" option; do
  case "${option}" in
    v) verbose=$1 ;;
    h) usage ;;
  esac
done

# helpers
function load_config() {
  source $ZSH_RC
}

# main
if [ -n "$verbose" ]; then 
  ZSH_VERBOSE=$1 load_config
else
  source $ZSH_RC
fi

