#!/bin/zsh
. prelude

# -- parsing --
Usage() {
  pu "[-hv]"
}

while getopts ":hv" option; do
  case "${option}" in
    v)  verbose=$1 ;;
    h*) Usage ;;
  esac
done

# -- commands --
LoadConfig() {
  # shellcheck source=/dev/null
  . "$ZSH_RC"
}

# -- main --
Main() {
  if [ -n "$verbose" ]; then
    ZSH_VERBOSE=$1 LoadConfig
  else
    LoadConfig
  fi
}

Main "$*"
