#!/bin/sh
. prelude

# -- parsing --
Usage() {
  echo "usage: rezsh [-hv]" 1>&2; exit 1;
}

while getopts ":hv" option; do
  case "${option}" in
    v)  verbose=$1 ;;
    h*) Usage ;;
  esac
done

# -- commands --
LoadConfig() {
  . $ZSH_RC
}

# main
if [ -n "$verbose" ]; then
  ZSH_VERBOSE=$1 LoadConfig
else
  LoadConfig
fi
