#!/bin/sh
. prelude

# -- parsing --
Usage() {
  pu "[-h] <list|module-name>" 1>&2; exit 1;
}

while getopts ":h" option; do
  case "${option}" in
    h*) Usage ;;
  esac
done

# -- commands --
List() {
  pt "modules"
  ListDir "$ZSH_RCD/pre"
  ListDir "$ZSH_RCD"
  ListDir "$ZSH_RCD/post"
}

ListDir() {
  \find $1/* -depth 0 -type f | sed -e "s|^$ZSH_RCD/||"
}

Edit() {
  if [ -z "$1" ]; then
    EditFile "$ZSH_RC"
  elif [ -f $ZSH_RCD/$1 ]; then
    EditFile "$ZSH_RCD/$1"
  else
    pe "'$1' is not a known module ${ga}(try 'zshrc list')"
  fi
}

EditFile() {
  $EDITOR "$1"
}

# -- main --
Main() {
  # dispatch command
  case "$1" in
    list) List ;;
    *)    Edit "$1" ;;
  esac
}

Main "$@"
