#!/bin/zsh

# starship
if [ "$(command -v starship)" ]; then
  eval "$(starship init zsh)"
fi

# direnv
if [ "$(command -v direnv)" ]; then
  eval "$(direnv hook zsh)"
fi

# rbenv
if [ "$(command -v rbenv)" ]; then
  eval "$(rbenv init - zsh)"
fi

# nvm
if [ "$(command -v nvm)" ]; then
  export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh
fi

# travis
if [ -f /Users/ty/.travis/travis.sh ]; then
  source /Users/ty/.travis/travis.sh
fi

# z
source /usr/local/etc/profile.d/z.sh

# fzf
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="$PATH:/usr/local/opt/fzf/bin"
fi

# fzf/auto-completion
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.zsh" 2> /dev/null

# fzf/key bindings
source "/usr/local/opt/fzf/shell/key-bindings.zsh"

# fzf/shortcuts
# cmd-o opens the file using "open" in fzf
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(open {})+abort'"

# tree
# source: https://geoff.greer.fm/lscolors/; TODO: port LSCOLORS->LS_COLORS conversion to sh
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

# ifttt
export DASH_CONFIG=/usr/local/dev-env
