#!/bin/zsh
printd "➜ step: update path"

# path directories (in priority-order)
path_dirs=(
  $HOME/.bin
  $HOME/.cargo/bin
  $HOME/.local/bin
  $HOME/.luxe/bin
  $HOME/Library/Android/sdk/platform-tools
  $HOME/Library/Python/3.7/bin
  $HOME/Library/Application\ Support/itch/apps/butler
  /opt/homebrew/bin
  /usr/bin
  /bin
  /opt/homebrew/sbin
  /usr/sbin
  /sbin
)

# add
PATH="$path_dirs[1]"
for path_dir in ${path_dirs:1}; do
  PATH="$PATH:$path_dir"
done

printd "✔ path: $PATH"

unset path_dirs

