#!/bin/zsh
printd "➜ step: update path"

# path directories (in priority-order)
path_dirs=(
  $HOME/.cargo/bin
  $HOME/Library/Android/sdk/platform-tools
  $HOME/bin
  $HOME/.bin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/local/sbin
  /usr/sbin
  /sbin
  ./bin
)

# add
PATH="$path_dirs[1]"
for path_dir in ${path_dirs:1}; do
  PATH="$PATH:$path_dir"
done

printd "✔ path: $PATH"

unset path_dirs

